version: 2

models:
  - name: stg_search_analysis
    columns:
      - name: title
        description: "Title of movie"
        tests:
          - unique
          - not_null
      - name: year
        description: "Release year"
        tests:
          - not_null
      - name: imdbrating
        description: "IMDB Rating"
        tests:
          - dbt_expectations.expect_column_to_exist
          - not_null
      - name: watch_priority
        description: "Analysis of watch priority"
        tests:
          - dbt_expectations.expect_column_to_exist
          - not_null     
      - name: synopsis
        description: "Summary of movie"
        tests:
          - dbt_expectations.expect_column_to_exist
          - not_null          
