version: 2

models:
  - name: stg_search_analysis
    columns:
      - name: id
        description: "Netflix ID"
        tests:
          - unique
      - name: title
        description: "Title of movie"
        tests:
          - not_null
      - name: year
        description: "Release year"
        tests:
          - not_null
      - name: imdbrating
        description: "IMDB Rating"
        tests:
          - not_null
      - name: watch_priority
        description: "Analysis of watch priority"
        tests:
          - not_null     
      - name: synopsis
        description: "Summary of movie"
        tests:
          - not_null
