version: 2

sources:
  - name: netflix_search
    database: ANALYTICS
    schema: PUBLIC
    tables:
      - name: SRC_NETFLIX_SEARCH
        loaded_at_field: updated_date
        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 5
            period: day