version: 2

sources:
  - name: netflix_search
    database: "{{ env_var('source_database') }}"
    schema: "{{ env_var('source_schema') }}"
    tables:
      - name: SRC_NETFLIX_SEARCH
        loaded_at_field: updated_date
        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 5
            period: day